### ISSUE TITLE
Status 200 OK instead of 403 (Forbidden)

### ISSUE THREAD

**Issue by Nikon99522** [php-youtube/php-blog#2]
Здравствуйте!
 У меня вопрос..., возможно многие пропустили, а возможно это только у меня так. Дело в том, что в главном контроллере (core/Controller.php) есть проверка :
```php
if (!$this->checkAcl()) {
	View::errorCode(403);
  }
```
Теперь есть два контроллера MainController.php и AdminController.php. И если с  MainController.php ACL работает хорошо, то этого не скажешь про AdminController.php ... Допустим страницу авторизации мы добавляем только для администраторов (для примера) и пробуем зайти на неё... Загружает application/views/errors/403.php, но если открыть "Инспектор кода" браузера и вкладку "Network" и нажмем клавишу F5, то увидим 200 OK (что есть не нормально).  То есть страница 403 и её стили подгружаются, а код 403 не приходит. 
Ситуация №2:
Существует MainController.php в нем 4 страницы, а одна из них это /about в acl для main.php разрешаем эту страницу для администратора и все также работает открывается application/views/errors/403.php, но самое главное отличие - отдает код 403.
Все скриншоты прилагаю ссылкой на Облако Mail.ru:
 https://cloud.mail.ru/public/5wcg/5EEmSGWFB
Почему так может происходить и что надо подправить? Может  что-то пропустил? Кстати, даже с $_SESSION['admin'] я не могу зайти на site.ru/admin.  
Заранее благодарен за любую подсказку!

**Comment by ArtemSannikov** [comment]
> Теперь есть два контроллера MainController.php и AdminController.php. И если с MainController.php ACL работает хорошо, то этого не скажешь про AdminController.php ... Допустим страницу авторизации мы добавляем только для администраторов (для примера) и пробуем зайти на неё... Загружает application/views/errors/403.php, но если открыть "Инспектор кода" браузера и вкладку "Network" и нажмем клавишу F5, то увидим 200 OK (что есть не нормально). То есть страница 403 и её стили подгружаются, а код 403 не приходит. Ситуация №2: Существует MainController.php в нем 4 страницы, а одна из них это /about в acl для main.php разрешаем эту страницу для администратора и все также работает открывается application/views/errors/403.php, но самое главное отличие - отдает код 403. Все скриншоты прилагаю ссылкой на Облако Mail.ru: https://cloud.mail.ru/public/5wcg/5EEmSGWFB Почему так может происходить и что надо подправить? Может что-то пропустил? Кстати, даже с $_SESSION['admin'] я не могу зайти на site.ru/admin. Заранее благодарен за любую подсказку!

Приветствую, вы в итоге решили свою проблему?

**Comment by Ioankoua** [comment]
вот сылка на мой гит, там все работает, проект не точь в точь, как в видео
но основа таже самая, может найдете что вам нужно
https://github.com/Ioankoua/Blog_on_MVS

вт, 28 сент. 2021 г. в 19:23, Artem ***@***.***>:

**Comment by Nikon99522** [comment]
Спасибо, проблема была решена.
